import streamlit as st
import pandas as pd
import pickle
import numpy as np

# --- 1. CONFIGURATION & MODEL RESTORATION ---
st.set_page_config(
    page_title="Kenyan Real Estate Valuation Engine",
    layout="wide"
)


@st.cache_resource
def load_production_pipeline():
    """
    Loads and caches the pickled LassoCV pipeline to ensure it only
    reads from disk once, keeping the app fast and responsive.
    """
    with open("ml_model/lasso_cv_model_2.pkl", "rb") as file:
        model = pickle.load(file)
    return model


try:
    loaded_pipeline = load_production_pipeline()
except FileNotFoundError:
    st.error(
        "⚠️ Production model file 'ml_model/lasso_cv_model_2.pkl' not found. Ensure it is saved in the 'ml_model' directory.")
    st.stop()

# --- 2. USER INTERFACE (DASHBOARD BANNER) ---
st.title(" Kenyan Real Estate Valuation Engine")
st.markdown("""
Enter the structural parameters and location profile of the property below 
to calculate an optimized market valuation generated by our tuned **LassoCV** baseline architecture.
""")
st.write("---")

# --- 3. INPUT COMPONENT GENERATION ---
st.subheader(" Property Features & Specifications")

col1, col2 = st.columns(2)

with col1:
    no_of_bedrooms = st.number_input(
        "Number of Bedrooms",
        min_value=1, max_value=10, value=3, step=1,
        help="Specify the total number of primary bedrooms."
    )

    property_type = st.selectbox(
        "Property Type",
        options=["Townhouse", "Villa"],
        help="Select the architectural structure classification."
    )

    has_servant_quarters = st.selectbox(
        "Has Servant Quarters (SQ)?",
        options=["Yes", "No"],
        help="Indicate if the compound incorporates an attached or detached SQ."
    )

with col2:
    #  display descriptive strings to the user for a premium user experience
    ui_zoning_tier = st.selectbox(
        "Zoning Tier Classification",
        options=[
            "Premium Suburbs (e.g Karen,Muthaiga,Kitisuru)",
            "High Density Upcoming Suburbs (e.g South B,South C,Ruaka)",
            "Kiambu/Thika Corridor (e.g Kenyatta Road,Kiambu Road)",
            "Satellite Towns (e.g Syokimau,Kitengela)",
            "Coastal Corridor (e.g Nyali,Kikambala)",
            "Premium Upcountry (e.g Nanyuki,Githunguri)"
        ],
        help="Select the planning permission development control zone."
    )


    if ui_zoning_tier == "Premium Suburbs (e.g Karen,Muthaiga,Kitisuru)":
        model_zoning_tier = "Premium Nairobi Suburbs"
        available_locations = ['Westlands', 'Lavington', 'Karen', 'Muthaiga', 'Kileleshwa', 'Kilimani', 'Gigiri',
                               'Loresho', 'Kitisuru']

    elif ui_zoning_tier == "High Density Upcoming Suburbs (e.g South B,South C,Ruaka)":
        model_zoning_tier = "High Density Upcoming Suburbs"
        available_locations = ["Lang'ata", 'South C', 'South B', 'Roysambu Area', 'Buruburu', 'Komarock', 'Donholm',
                               'Embakasi / Eastlands']

    elif ui_zoning_tier == "Kiambu/Thika Corridor (e.g Kenyatta Road,Kiambu Road)":
        model_zoning_tier = "Kiambu/Thika_Road Corridor"
        available_locations = ['Kiambu Road', 'Ruiru', 'Thika', 'Juja / Kenyatta Road']

    elif ui_zoning_tier == "Satellite Towns (e.g Syokimau,Kitengela)":
        model_zoning_tier = "SatelliteTowns/Commuter Belt"
        available_locations = ['Kitengela', 'Syokimau', 'Ngong', 'Ongata Rongai', 'Athi River', 'Kikuyu',
                               'Kamulu/Joska/Eastern Bypass', 'Limuru/Tigoni', 'Mombasa Road / Syokimau', 'Isinya']

    elif ui_zoning_tier == "Coastal Corridor (e.g Nyali,Kikambala)":
        model_zoning_tier = "Coastal Market Corridor"
        available_locations = ['Nyali', 'Mtwapa', 'Mombasa', 'Kilifi/kikambala/Mtwapa', 'Diani', 'Watamu', 'Malindi']

    else:
        model_zoning_tier = "Upcountry Luxury Zone"
        available_locations = ['Naivasha', 'Nanyuki', 'Kisumu', "Murang'a County", 'Kamangu', 'Githunguri', 'Gilgil',
                               'Oltepesi Kajiado County', 'Oltepesi', 'Kajiado County', 'EPZ, Kajiado County']

    location = st.selectbox(
        "Geographic Location",
        options=available_locations,
        help="Select the primary neighborhood zone."
    )

# --- 4. DATA COMPILATION & LIVE PREDICTION ---
st.write("---")

sq_mapping = 1 if has_servant_quarters == "Yes" else 0


input_data = {
    "no_of_bedrooms": no_of_bedrooms,
    "has_servant_quarters": sq_mapping,
    "property_type": property_type,
    "clean_location": location,
    "zoning_tier": model_zoning_tier
}

# Convert compiled dictionary to a single-row DataFrame
input_df = pd.DataFrame([input_data])

# Valuation execution trigger button
if st.button("Calculate Market Valuation", type="primary"):
    with st.spinner("Executing core matrix alignment optimization..."):
        try:
            # Pass the raw DataFrame right into the loaded pickle pipeline
            raw_prediction = loaded_pipeline.predict(input_df)[0]

            # Prevent negative boundary valuations if structural weights skew extreme
            final_valuation = max(0, raw_prediction)

            # --- 5. RENDER PRESENTATION RESULTS ---
            st.success(" Valuation Successfully Calculated")
            st.metric(
                label="Estimated Market Value",
                value=f"KSh {final_valuation:,.2f}"
            )

            st.caption(
                "This market valuation is a machine learning estimate, not an official property valuation.")

        except Exception as e:
            st.error(f"Prediction execution failed: {e}")
            st.info("Check your column transformer settings if feature shapes change in your notebook workbench.")